# ================= SERVER =================
server.port=8081
spring.application.name=auth-service

# ================= EUREKA =================
eureka.client.service-url.defaultZone=http://eureka-server.infra.svc.cluster.local:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# ================= DATABASE =================
spring.datasource.url=jdbc:mysql://mysql.infra.svc.cluster.local:3306/authdb?createDatabaseIfNotExist=true&useSSL=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ================= JPA =================
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ================= JWT =================
jwt.secret=${JWT_SECRET}
jwt.expiration=28800000
jwt.refresh-expiration=604800000

# ================= ACTUATOR =================
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

# ================= AUDIT LOG SERVICE =================
audit.service.url=http://audit-log-service.apps.svc.cluster.local:8085/api/audit/log
