apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pfe-dev
  namespace: argocd
spec:
  project: pfe-2026
  source:
    repoURL: https://github.com/makremTaieb/devsecops-monta.git
    targetRevision: dev
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
