apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pfe-staging
  namespace: argocd
spec:
  project: pfe-2026
  source:
    repoURL: https://github.com/makremTaieb/devsecops-monta.git
    targetRevision: staging
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
