apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pfe-2026
  namespace: argocd
spec:
  description: STB DevSecOps Platform
  sourceRepos:
    - https://github.com/makremTaieb/devsecops-monta.git
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: staging
      server: https://kubernetes.default.svc
    - namespace: prod
      server: https://kubernetes.default.svc
    - namespace: infra
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
