server.port=8082
spring.application.name=pipeline-service

spring.datasource.url=jdbc:mysql://mysql.infra.svc.cluster.local:3306/pipelinedb?createDatabaseIfNotExist=true&useSSL=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://eureka-server.infra.svc.cluster.local:8761/eureka/
eureka.instance.prefer-ip-address=true

feign.client.config.default.connect-timeout=5000
feign.client.config.default.read-timeout=30000

jenkins.url=http://192.168.56.10:8080
jenkins.username=${JENKINS_USERNAME:admin}
jenkins.token=${JENKINS_API_TOKEN}

security.scan.threshold=70.0

jwt.secret=${JWT_SECRET}
jwt.expiration=28800000

spring.task.execution.pool.core-size=4
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=50
spring.task.execution.thread-name-prefix=jenkins-tracker-

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

# ================= AUDIT LOG SERVICE =================
audit.service.url=http://audit-log-service.apps.svc.cluster.local:8085/api/audit/log

# ================= NOTIFICATION SERVICE =================
notification.service.url=http://notification-service:8087/api/notifications/pipeline-event
